version: '3.8'

services:
  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6379:6379'
  mock-xero:
    image: jaypeng2015/show-me-the-money
    container_name: mock-xero
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./balance-sheet-reports-backend
    container_name: backend
    ports:
      - "3007:3007"
    env_file:
      - .env
    depends_on:
      - redis
      - mock-xero

  frontend:
    build:
      context: ./balance-sheet-reports-frontend
    ports:
      - "80:80"